# Ferhat Yiğit Aydın
# 02.07.2025

CXX = g++
CXXFLAGS = -std=c++17 -Wall -O2
TARGET = main
SRC = main.cpp

all: $(TARGET)

$(TARGET): $(SRC)
	$(CXX) $(CXXFLAGS) -o $(TARGET) $(SRC)

clean:
	rm -f $(TARGET)
